# Generated by Django 4.2.2 on 2024-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_familia', models.PositiveIntegerField(null=True)),
                ('nombre_flia', models.CharField(max_length=150)),
            ],
        ),
    ]
