# Generated by Django 4.2.2 on 2024-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nombre_flia',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
