# Generated by Django 4.2.2 on 2026-09-17 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_alter_familia_nombre_flia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCensoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.CharField(max_length=150)),
                ('integrantes_previstos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_censo', to='familias.familia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='metacensofamiliar',
            constraint=models.UniqueConstraint(fields=('familia', 'vigencia'), name='meta_familia_vigencia_unica'),
        ),
    ]
