# Generated by Django 4.2.2 on 2024-05-18 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('censos', '0002_remove_censo_persona_id_censo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('T', 'Terminada'), ('E', 'En Transcurso'), ('P', 'Pendiente')], default='P', max_length=1)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censos.censo')),
            ],
        ),
    ]
