# Generated by Django 4.2.2 on 2024-05-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('censos', '0002_remove_censo_persona_id_censo_persona'),
        ('censo_actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censoactividad',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.actividad'),
        ),
        migrations.AlterField(
            model_name='censoactividad',
            name='censo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censos.censo'),
        ),
    ]
