# Generated by Django 4.2.2 on 2026-09-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo_actividades', '0002_alter_censoactividad_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censoactividad',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='censoactividad',
            name='estado',
            field=models.CharField(choices=[('T', 'Terminada'), ('E', 'En Transcurso'), ('P', 'Pendiente'), ('N', 'No realizada')], default='P', max_length=1),
        ),
    ]
