# Generated by Django 4.2.2 on 2024-05-15 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.CharField(max_length=150)),
                ('resguardo_ind', models.PositiveIntegerField(null=True)),
                ('comunidad_ind', models.PositiveIntegerField(null=True)),
                ('persona_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.persona')),
            ],
        ),
    ]
