# Generated by Django 4.2.2 on 2024-05-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('censos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censo',
            name='persona_id',
        ),
        migrations.AddField(
            model_name='censo',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.persona'),
        ),
    ]
