# Generated by Django 4.2.2 on 2024-06-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censos', '0002_remove_censo_persona_id_censo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='censo',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
