# Generated by Django 4.2.2 on 2026-09-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censos', '0003_censo_documento_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censo',
            name='documento_pdf',
        ),
    ]
