# Generated by Django 4.2.2 on 2024-05-18 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('censo_actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('censo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='censo_actividades.censoactividad')),
            ],
        ),
    ]
