# Generated by Django 4.2.2 on 2024-05-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
