# Generated by Django 4.2.2 on 2026-09-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula'), ('RC', 'Registro Civil'), ('NUIP', 'Numero único de Identificación Personal'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria')], max_length=4, null=True),
        ),
    ]
