# Generated by Django 4.2.2 on 2026-09-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='', max_length=2),
        ),
    ]
